# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 61a305c0ca1b5fdc83e719f4b72fc174d3648da6e2ddfbe092268fb6862f75fefdeedc633aa83024eed2bc1ce6aa35f70e57248782f7c1bf772d5d3c108307fe
  pubnub_subscribe_key: sub-c-37db8cd8-e7f3-11e6-b325-02ee2ddab7fe
  pubnub_publish_key: pub-c-7806e808-b932-4da2-9b0a-32ffbb4e854e
  pubnub_secret_key: sub-c-37db8cd8-e7f3-11e6-b325-02ee2ddab7fe
  pubnub_auth_key: happy-new-year

test:
  secret_key_base: 9adab0f7414f2cfdcb91c466451a78e32f38ba20edb4563f08151ac971433a2b30578cf11d79098fa41f5a38009335615bea3196bbfc421cf775fb9a5ef80053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
